[toolchain]
anchor_version = "1.2.0"
solana_version = "3.1.10"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cometail_vault = "5xmZWYheruQjHQChg5YVtXjZUNmVKzvjJ6FYArtf4tmg"
cometail_burn = "BuN6MuTRCD7VuzwRpvJKPFwh86bsU81L23tKtRBofhX1"

[programs.devnet]
cometail_vault = "5xmZWYheruQjHQChg5YVtXjZUNmVKzvjJ6FYArtf4tmg"
cometail_burn = "BuN6MuTRCD7VuzwRpvJKPFwh86bsU81L23tKtRBofhX1"

[provider]
cluster = "localnet"
wallet = "keys/local/payer.json"

[scripts]
test = "pnpm --filter @cometail/tests test"

[test]
startup_wait = 5000
